export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';


export const CART_ITEMS_REQUEST = 'CART_ITEMS_REQUEST';
export const CART_ITEMS_SUCCESS = 'CART_ITEMS_SUCCESS';
export const CART_ITEMS_FAILED = 'CART_ITEMS_FAILED';